#!/bin/sh
#
# Contributed & written by: Dan Lowe <dan@tangledhelix.com>
# This used to be in the main MiG distribution but is now deprecated and
# can be found here in the contrib directory.
#
# calls mf_conv recursively to do subfolders
#
# You'll want to grab mf_conv from the contrib directory too.
#

conv="`dirname $0`/mf_conv"

echo "Converting MiG metafiles..."
echo " "

find . -type d -print > /tmp/$$.mv_conv
${conv} -I /tmp/$$.mv_conv
rm /tmp/$$.mv_conv

