version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "saturday"
    groups:
      all-actions:
        patterns: [ "*" ]

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "saturday"
    groups:
      all-composer:
        patterns: [ "*" ]
