$Revision$


=pod

Z<>

=head1 MIG CHANGE LOG

Z<>

=head2 Version 1.3.0 (NOT YET RELEASED)

Added TITLE tags in thumbnail views so when hovering over a thumbnail,
you get the comment whether using Mozilla/Gecko/Netscape or Internet
Explorer.  C<$suppressAltTags> will also suppress the TITLE tags.

Added Polish translation.

=head2 Version 1.2.9 (Thu 16 Aug 2001)

Added C<$imagePopup> and C<$imagePopType> to F<mig.cfg.default>.  Using these
one can have pop-up windows enabled.  See F<docs/INSTALL>.

[Sourceforge bug report #441188] -
Fixed a bug in the handling of C<$viewFolderCount>.  Previously, if a
folder was mentioned in a E<lt>sortE<gt> block, it would be ignored when
C<$viewFolderCount> was evaluated.  Now C<$viewFolderCount> is properly
applied to all folders that contain images, whether they are sorted or
not.

[Sourceforge bug report #442760] -
Fixed a bug in getExifDescription.  The string &quot;flash used&quot;
was hard-coded rather than being included in the language library.

Upgraded to most recent revision of jhead to get ISO rating support.

Added ISO rating to EXIF info parser.

Fixed bug in ALT tag (there was no space before the SRC and ALT bits).

=head2 Version 1.2.8 (Fri 29 Jun 2001)

Added Italian and Spanish translations

[Sourceforge feature request #416337] - 
Modified the ALT tag code such that HTML entities within E<lt>commentE<gt>
blocks should be OK now even if hover-over comments are being used
in thumbnail views.

Added Slovak and Dutch translations

[Sourceforge feature request #414831] -
Added C<$viewCamInfo> to F<mig.cfg.default>.  If set to C<TRUE> and an
F<exif.inf> is present in a given gallery folder, it will be read to try to
extract camera model, and frame exposure information for display on the
page.

[Sourceforge feature request #424166] -
Added C<$viewFolderCount> to F<mig.cfg.default>.  If set to C<TRUE>, the
number of images in a given folder will be displayed next to the folder's
name in parentheses, in a folder list view.

[Sourceforge feature request #414827] -
Added C<FolderIcon> entity to F<mig.cf> parser.  Lets you define something
other than F<folder.gif> as the icon for a folder.  You can define each
folder with any icon you want.  Default is still F<folder.gif>.

[Sourceforge feature request #414827] -
Added C<FolderTemplate> entity to F<mig.cf> parser.  This allows for a
template file to be defined within the folder itself, specific to that
folder.  Or you can define a full path if you wanted.

[Sourceforge feature request #414827] -
Added C<PageTitle> entity to F<mig.cf> parser.  Allows for a per-folder
pageTitle to be set.

[Sourceforge feature request #414827] -
Added C<MaxFolderColumns> and C<MaxThumbColumns> entities to F<mig.cf>
parser.  This permits custom column settings per folder.

=head2 Version 1.2.7p1 (Sun Apr 15 2001)

Fixed bug from 1.2.7 which caused images to show up as folders when both
folders and images were present.

=head2 Version 1.2.7 (Sat Apr 14 2001)

Added Danish translation

Modified template parser so that you can use #include to include PHP files
(files with extensions ".php" or ".php3")

Added docs/FTPinstall.txt for people who have only FTP access to their
server and no shell access (i.e. they can't run F<install.sh>).

Streamlined code where possible

Got rid of repeated parses of mig.cf in subroutines and created
parseMigCf() to just do it once to save time and effort on file i/o.

=head2 Version 1.2.4 (Mon Apr 09 2001)

Added Swedish translation

Removed all calls to die() since they seemed to not work in all versions
of PHP.

=head2 Version 1.2.3 (Mon Apr 09 2001)

Removed install.bat, rewrote docs/Windows.txt to match.

Rewrote install.sh for new directory layout (which was a side-effect of
making Windows installs easier).

Adjusted all server variables so that things should work whether
register_globals or track_vars are in use (or both).

Found a hard-coded directory in printTemplate() - corrected.

=head2 Version 1.2.2 (Sun Apr 08 2001)

Added language definition for Turkish

Changed all occurrences of C<$language> to C<$mig_language> because of a
suspected conflict with a variable name in PHP-Nuke.

=head2 Version 1.2.1 (Fri Apr 06 2001)

Fixed a bug where folks with C<track_vars = Off> would break.

Added definitions for Russian Windows-1251 and Russian KOI8-R

=head2 Version 1.2 (Fri Apr 06 2001)

Added C<$suppressAltTags> to F<mig.cfg> - when set to C<TRUE>, ALT tags are
not added in thumbnail lists.

Added C<$useVirtual> in F<mig.cfg> - when set to C<FALSE>, C<virtual()> is
not tried.  This is for people who for some reason don't have C<virtual()>
support in their PHP installation.

Fixed C<printTemplate()> so it only fetches the image size if there's an
image to fetch the size for.  This had been causing a problem under some
conditions.

Added multi-language support (so far English and French translations).  See
the C<$language> variable in F<mig.cfg.default>.  (Note this variable is
known as C<$mig_language> as of version 1.2.2)

Added C<$sortType> to F<mig.cfg.default>.

Fixed bug that caused trouble with folks not using C<register_globals>.

Added definitions for German, Norwegian, Portugese, Finnish, Romanian.

=head2 Version 1.1 (Thu Dec 28 2000)

Added F<docs/Apache.txt> with useful tips and tricks for Apache users.

Added support for password-protected folders.  See F<docs/Passwords.txt>.

Added support for thumbnail subdirectories.  See F<docs/Install.txt>,
F<docs/Utilities.txt>, and F<mig.cfg.default>.

Added code to accomodate sites using C<magic_quotes_gpc>.

Fixed bug with C<PATH_INFO> jump tags.

Added C<$noThumbs> boolean to F<mig.cfg.default>.  See F<docs/Install.txt>.

Added C<$thumbExt> to F<mig.cfg.default>.  See F<docs/Install.txt>.

Fixed bug in C<parseMyConfig()> in F<mkGallery> which caused a bad data set
to be returned if the config file couldn't be read.

Rewrote F<mkGallery> to accomodate C<$thumbExt>.

Upgraded the bundled F<jhead> distribution to 1.0.  Updated F<install.sh>
and F<mkGallery> to accomodate.  No action on the part of users should be
needed since the command-line syntax and output format of F<jhead> is the
same.

(Duh!)  Added Matthias Wendel (author of F<jhead>) to F<docs/Credits.txt>.

Turned C<magic_quotes_runtime> off by default - we don't do anything in a
write mode and I don't see any advantage or safety offered by
C<magic_quotes> for this application.

Using C<$HTTP_GET_VARS> array now for people using C<register_globals = Off>.

Will start distributing .ZIP and .tar.gz formats from now on.

Added C<$maxThumbColumns> and C<$maxFolderColumns> to F<mig.cfg.default>.
C<$maxColumns>, if present, will be used as the default value of
C<$maxThumbColumns>.  This lets people use something other than a single
column for folder listings.

=head2 Version 1.0 (Wed Dec 06 2000)

You can now type "quit" at any prompt during F<install.sh> to abort.

F<install.sh> and PHP code revamped and retested for PHP-Nuke compatible
mode.  Now the MiG install (except for F<mig.php> and F<mig.cfg>) are
sandboxed into the F<mig> subdirectory rather than being right in the base
PHP-Nuke directory.

Changed F<mig.cfg.default> to use C<TRUE> & C<FALSE> rather than 1 and 0
for boolean options.

Added C<$suppressImageInfo> to F<mig.cfg.default> - boolean option which
controls whether to suppress the information printed below thumbnail images
on thumbnail view pages.

=head2 Version 0.99 (Thu Nov 16 2000)

Not an enhancement, but I finally got around to trying out symlinks.  Put a
bit about this in F<docs/Install.txt>.

Added a new file F<docs/Credits.txt> where I will credit folks who have
contributed bits of code, found bugs, etc.

Added PHP-Nuke compatibility mode (see F<docs/phpNuke.txt>).  Only of
interest to folks using, or interested in using, PHP-Nuke.

Updated F<install.sh> for phpNuke mode, and tried to make it a little
smarter about some things.

Removed F<convert-metafiles> from the main distribution and make it a
contrib script instead.  F<mf_conv.pl>, too.

Added the C<PATH_INFO> method for Jump URLs.  See F<docs/Jump.txt>.

Added -n and -r switches to F<mkGallery>.  See F<docs/Utilities.txt>.

Revamped C<#include> for Apache users so it can execute CGI's too.  See
F<docs/Templates.txt>.

Fixed C<buildNextPrevLinks()> to use an array as its return value instead
of the (uglier) string concatenation method.

=head2 Version 0.98 (Sun Nov 05 2000)

Added jump URL tags.  See F<docs/Jump.txt> for more information.

=head2 Version 0.97 (Sat Nov 04 2000)

Fixed table formatting problem in C<imageFrame()> which caused an extra
cell to be printed which was visible as a small line in IE browsers.

=head2 Version 0.96 (Thu Nov 02 2000)

Updated F<docs/Install.txt> with notes about file permissions.

Fixed bug in C<buildNextPrevLinks()> - it was ignoring E<lt>SortE<gt>
lists.

=head2 Version 0.95 (Tue Oct 31 2000)

Ran the example gallery through a C<mogrify -quality 40> to reduce the size
of the download tarball.  Went from just over 600KB to about 340KB.
Amazingly, I can't even tell the difference viewing the images.

Removed a hard-coded value from C<buildImageURL()> which broke things for
folks who had changed the value of C<$albumDir>.  It was found in three
places inside that function.

Made the terms of the licensing clearer according to the FSF GNU
guidelines at http://www.gnu.org/copyleft/gpl.html .

Did a code review looking for potential problems, made minor adjustments.

Added interactive (-i) mode to F<util/mkGallery>.  See
F<docs/Utilities.txt>.

Happy Halloween!

=head2 Version 0.94 (Sat Oct 28 2000)

F<mkGallery> will now sort items before handling them, so output files like
the comment file will have items alphabetically (for simplicity).

Fixed bug in C<buildDirList()> that didn't do the rendering of spaces and
underscores correctly (they should be rendered as C<&nbsp;>).

Fixed rather large bug in C<buildDirList()> which caused cascading links
in the output HTML.  This was not very noticeable until one had a large
list of folders (where large is just a few tens of directories).  A string
was not being properly reset at the beginning of each loop iteration.

=head2 Version 0.93 (Tue 17 Oct 2000)

Added a question to F<install.sh> which asks the user if they are upgrading
from 0.83 or earlier (so not everyone for the rest of time has to run
F<convert-metafiles> anytime they upgrade).

F<install.sh> will no longer try to guess what directory to install into.

Discovered that when moving from one page to the next, the
C<text-decoration> CSS property for anchors (E<lt>AE<gt> elements) was not
reset.  So if you set C<text-decoration=none> it would memorize that and
not go back to using underlines.  So I defined C<A:*> as having
C<text-decoration=underline> in F<templates/style.css> (which is what you'd
expect to see becaues most browsers underline links by default).

Changed link on image view pages that goes back to read "back to thumbnail
view".  Previously it read "back to folder view" but it has been pointed
out to me that the wording was confusing.

Discovered the amazing function C<GetImageSize()>.  Now all thumbnail views
will use C<width= height=> for the thumbnails (this helps speed up the
browser's rendering of tables), and thumbnail views now show the image size
in both pixels and bytes.  Single image views will use C<width= height=> as
well, to help the browser in its rendering task.

Added new tag C<%%imageSize%%> to the F<image.html> template.

Switched from using C<$SCRIPT_NAME> to using C<$PHP_SELF>.  This basically
means MiG should work for people using PHP's CGI mode now.

Implemented E<lt>SortE<gt> element in F<mig.cf> - see F<docs/mig_cf.txt>.

=head2 Version 0.92 (Mon 02 Oct 2000)

Plugged a security hole (C<$currDir> wasn't being checked for '..') which
let viewers see the entire directory stucture of a system.  Anyone using
anything prior to 0.92 should upgrade immediately!

=head2 Version 0.91 (Sat 30 Sep 2000)

Fixed a bug in F<mf_conv.pl> which caused the comment conversion process to
cascade itself... it stored a list of images and comments in memory, but
when it entered a new directory it was not cleaning that out, so every
F<mig.cf> had comments for all the files in all the directories it had seen
before.  Not particularly dangerous but it litters your F<mig.cf> files
badly.  This is only a problem for folks who upgraded from a release of MiG
version 0.83 or earlier to MiG 0.90.

=head2 Version 0.90 (Sat 30 Sep 2000)

Created F<install.sh> to act as an installer script.  Reorganized the
directory structure somewhat while doing this.

Updated all documentation.

Added the C<#include> directive to the template processor.  See the file
F<docs/Templates.txt> for information.

Added Windows doc F<docs/Windows.txt> for Windows users.  Working on .EXE
automatic-style installation program.

Changed name of EXIF header cache file to F<exif.inf>.

Because F<install.sh> checks for existing template files and tries to
figure out the proper thing to do (asking for input if needed), hopefully
the risk of the installation process blowing away customized templates has
been eliminated (or at least reduced greatly).  Well, unless you happen to
use Windows, where I have less versatility with installation processes.
See F<docs/Windows.txt> for notes on that topic.

Devised Apache-like format for meta file F<mig.cf> which will hold
comments, hidden file lists, etc.  This will replace F<.comments.txt>,
F<.hidden.txt>, etc.  EXIF header info will still live in F<exif.inf>
(formerly known as F<.exif_comments.txt>).  Documentation is in
F<docs/mig_cf.txt>.

Updated all files to reflect new domain "tangledhelix.com".

Converted all colorization to use CSS stylesheets.  However, Netscape
doesn't behave regarding the C<BODY> element and CSS, based on my tests.
So there's a default color set in the C<BODY> tag in the HTML templates.
See the file F<docs/Templates.txt> for more information.

Added tag C<%%distURL%%> for templates.  Removed "MiG" from E<lt>TITLEE<gt>
in the default templates.

Added script F<convert-metafiles> to convert metafiles to new format.
It calls a Perl child process, F<mf_conv.pl>.

Installer tries to find Perl and if so, sets the #! line for Perl-based
utility scripts.  This is because folks have Perl installed in places that
are hard to predict but which are probably in their C<$PATH>.

Added E<lt>BulletinE<gt> feature to F<mig.cf>.  See F<docs/mig_cf.txt> for
info.

"_" (underscore) is now rendered as a space character in the YouAreHere
line as well as in the folder-list boxes.

Got E<lt>CommentE<gt> working, got EXIF parsing working.

Now in folder / thumbnail views, image comments are loaded as ALT tags,
so they will pop-up as text when you hover over a link.

Fixed bug which caused images with spaces in their filename to be handled
improperly.

Added C<$markerType> and C<$markerText> to F<mig.cfg.default>.  Added C<-m>
and C<-M> flags to F<mkGallery>.  These were added to support customizable
thumbnail naming conventions.  You can now decide what thumbnail marker
name to use (previously was forced to be "th".  Also now you can declare it
to be a prefix (as in "th_filename.JPG") or a suffix (as in
"filename_th.JPG").  Default will be as previous, suffix mode using "th"
for filename_th.JPG.  See F<docs/Utilities.txt> and F<docs/Install.txt> and
F<mig.cfg.default> for more information.

Updated F<mkGallery> to read C<$markerType> and C<$markerLabel> from
F<mig.cfg>, so you don't have to worry about the C<-M> and C<-m> flags as
long as your F<mig.cfg> has the right options set.

Changed C<slashFixedURLencode()> to C<migURLencode()>.

Fixed bug in C<migURLencode()> where it would re-encode something which was
already encoded resulting in a comma becoming C<%252C> instead of say,
C<%2C>.  It now runs input through C<rawurldecode()> prior to doing a
C<rawurlencode()> on it.

Added C<-c> option to F<mkGallery> - this will populate the F<mig.cf> file
with blank E<lt>CommentE<gt> elements.  It was adapted from F<mkComments>,
which was contributed by André Fadel (fadel F<at> fee.unicamp.br).  See
F<docs/Utilities.txt> for information.

Fixed bug in C<getExifDescription()> which was returning incorrect values.

Found bug in the F<convert-metafiles> script which caused directories with
spaces in the filename to wig the script out.  Fixed.

Fixed bug in regex used to find comment lines in C<getExifDescription()>
which would cause extremely long execution times when dealing with large
F<exif.inf> files.

Fixed bug which caused improper display of filesizes in thumbnail views.

=head2 Version 0.83 (Thu 24 Aug 2000)

Images and folders are now sorted alphabetically, to make the sorting
consistent, if not (yet) completely customizable.

=head2 Version 0.82 (Thu 24 Aug 2000)

Fixed bug in F<mkGallery> that caused problems parsing filenames with
embedded spaces.

=head2 Version 0.81 (Sat 12 Aug 2000)

Changed the behavior of C<buildYouAreHere()> so the browser can't click on
the current item - that is, the current folder or the current image.  It
just seemed silly to recreate the browser's reload button.

=head2 Version 0.80 (Sat 12 Aug 2000)

The pieces of the "you are here" headline are now clickable for simpler
navigation between levels.

Changed the style sheet so the links are underlined again.  People aren't
used to having it any other way, it was causing confusion.

Got C<newCurrDir> out of the URI string which makes the URL about 50% as
long as before.  This entailed adding C<getNewCurrDir()> calls.

=head2 Version 0.77 (Sat 12 Aug 2000)

Added style sheet support.  See the file F<templates/style.css>.

=head2 Version 0.76 (Fri 11 Aug 2000)

Rearranged the layout in F<image.html> to make it friendlier for small
screens.

=head2 Version 0.75 (Tue 08 Aug 2000)

Fixed overpadded image tables.

=head2 Version 0.74 (Mon 07 Aug 2000)

Cleaned up the HTML layout (mostly shuffling, adding, deleting
E<lt>BRE<gt>).

=head2 Version 0.73 (Mon 07 Aug 2000)

Added a "now viewing #x of y" in image views, so the browser can easily
tell how many images are left in either direction without returning to the
thumbnail view.

=head2 Version 0.72 (Mon 07 Aug 2000)

Using colored table cells for comments now.  Embedded comments are
seperated from file-based comments with an E<lt>HRE<gt> element.

=head2 Version 0.71 (Mon 07 Aug 2000)

Descriptions are centered now.

=head2 Version 0.70 (Mon 07 Aug 2000)

Bundled F<jhead> from Matthias Wandel in order to parse EXIF headers.
F<jhead> will be a child process of F<mkGallery> when invoked with C<-e>.

Updated F<mkGallery> with new options and code to handle parsing of EXIF
headers using the F<jhead> program.  See the C<-e> and C<-w> options.  Also
added a C<-t> option to specify if you should make thumbnails or not (since
that's not the only action possible anymore).

Added function C<getExifDescription()> which parses the
F<.exif_comments.txt> files for embedded comments and displays them in
image views.  (This file is known as F<exif.inf> as of the 0.90 release)

=head2 Version 0.61 (Sun 06 Aug 2000)

Added "you are here" line, but it's not clickable yet.

=head2 Version 0.60 (Sun 06 Aug 2000)

Added "hidden" feature.  Anything put into F<.hidden.txt> in a directory
will cause the listed items (one per line) to be rendered invisible.
This is, of course, optional.

Cleaned up places where C<eregi()> or C<eregi_replace()> were used when the
proper call was C<ereg()> or C<ereg_replace()>.

Added "comment" feature.  Comments are stored in F<.comments.txt>.  See
F<INSTALL> for more information.

=head2 Version 0.51 (Sun 06 Aug 2000)

Added C<$homeLink> and C<$homeLabel> to config, to print a "back to {home}"
link at the "root" folder level.

=head2 Version 0.50 (Sat 05 Aug 2000)

Set default colors so if C<$imageBGcolor> and/or C<$folderBGcolor> are
missing in the config, it won't default to black.

Set default C<$maxColumns> in case that is omitted from config file.

Set default C<$title> in case that is omitted from config file.

Set default C<$maintAddr> in case that is omitted from config file.

Got next/previous links working in image views

Removed "back" link from "main" or "root" of album.

=head2 Version 0.41 (Fri 04 Aug 2000)

Fixed font size bug with back link on "main" page.

=head2 Version 0.40 (Fri 04 Aug 2000)

Rewrote F<mkGallery> with C<use strict> and C<-w>

Symlinked F<index.php3> to F<index.php> for simplicity.

Replaced "E<lt>E<lt>" in C<buildBackLink()> with C<&lt;&lt;> and cleaned up
other such bits throughout the code.

Replaced most spaces in templates & PHP with C<&nbsp;> due to odd
formatting problems with MSIE.

Wrote table generation code into PHP and took it out of the template files
due to MSIE's stupid insistence on displaying empty tables with a tiny
colored square.

Cleaned up (simplified) templates a little.

Added variables C<$imageBGcolor> and C<$folderBGcolor>, which are
background colors for the table backgrounds for the image and folder
tables, respectively.  They can be found in F<mig.cfg.default>.

Documented templates in F<templates/README.templates>.  (This can now be
found in F<docs/Templates.txt> as of 0.90)

=head2 Version 0.36 (Tue 01 Aug 2000)

Got rid of C<$phpExt> - include files aren't seen by the web server anyway,
so the extension wasn't relevant.

=head2 Version 0.35 (Tue 01 Aug 2000)

Reworked page formatting.  Now if there are no folders and no images
present, the browser gets "No contents".  If no folders, the folder table
isn't printed.  If no images, the images table isn't printed.  If there are
both, you see both tables.  The result is less confusing.

If F<mig.cfg> is missing, F<mig.cfg.default> will be read instead, to avoid
any errors popping up. 

=head2 Version 0.34 (Mon 31 Jul 2000)

Added a second back link to each page since pages can grow long enough that
having one at the top and one at the bottom is desirable.

=head2 Version 0.33 (Mon 31 Jul 2000)

Added filesize to the thumbnails page

=head2 Version 0.32 (Mon 31 Jul 2000)

Fixed a stupid bug (C<$maxColumns> was being ignored).  Table layouts on
thumbnail pages should work now.

=head2 Version 0.31 (Mon 31 Jul 2000)

If a thumbnail is missing, a generic image will be used in its place.

=head2 Version 0.3 (Mon 31 Jul 2000)

The "back" link is now grayed out when at the "main" page.

Fixed bug in F<mkGallery> that would cause it to create thumbnails of
already-existing thumbnail images.

Viewing a folder will now show the thumbnail images correctly.

Added template F<image.html> to view individual images.

Removed the "you are at" headline, the help function, and the "exit"
button.  The latter two were never too useful, and the former is a real
pain to get working.  I'll save it for some future release.

Added C<$phpExt> variable for PHP3 users who might need filenames with
C<.php3> extensions instead of C<.php>.

Added C<$pageTitle> to insert into the E<lt>TITLEE<gt> element of each
template.

Removed C<*currLocation> routines

Started using F<mig.cfg.default> for dist bundles to avoid over-writing old
config files.

Fixed a bug which caused image view "back" links to go not to the previous
page, but literally to "../"

Fixed URL pointer in the HTML templates to reflect correct MiG distribution
URL.

=head2 Version 0.2 (Sun 30 Jul 2000)

The F<mkGallery> utility script is complete.  Requires Perl and
ImageMagick.  No other significant changes in 0.2.

=head2 Version 0.1 (Fri 28 Jul 2000)

Got "any directory anywhere" directory browsing working correctly.  An
album can have any number of directories and subdirectories now.  This is
much better than the old 2-level directory model.

Changed direction on the topic of thumbnail generation.  It's better to
pre-generate them instead of having the PHP code do it on the fly.  Having
the script get reliable write access to the filesystem proved to be a bit
more sloppy than I originally thought.

The old method of using numeric filenames is gone now (thank god).

Support for JPEG/GIF/PNG formats should be good enough.  Old model of
supporting only one file type sucked.

Nailed down an HTML layout finally, simpler than others I have seen, more
attractive than the previous ones used in F<album.php3>.

Got HTML templates working.

Added a help link, back link, and a mailto: link to each page.  Each page
also has a link back to the distribution URL.

Got the "you are here" path to display, but no links yet.

Got rid of the old problem from F<album.php3> where the path had to be
statically set in the code ahead of time (and the fact that tilde-URLs like
C</~dan/> didn't work).  This time around the script figures out where it
is in the filesystem and bases everything else on that path.

Added the "exit" link to take browser to an outside URL.

=cut

