$Id$


=pod

Z<>

=head1 USING MIG WITH PHP-NUKE

Z<>

MiG has a "PHP-Nuke Compatible" mode which you can use to merge MiG into
your PHP-Nuke-based site.  If you don't know what PHP-Nuke is, you probably
don't need to continue reading this file.

PHP-Nuke information can be found at http://www.phpnuke.org/

Please read F<docs/INSTALL> and then apply the following changes.

1. When the install script asks if you want to use PHP-Nuke, answer "y".

2. It will then make a few adjustments to customize to fit the PHP-Nuke
way of doing things.

3. When the install is finished, you will have a subdirectory F<mig> in
your main PHP-Nuke site directory.  Everything related to MiG is stored
in that subdirectory, with one exception: F<mig.php>.  That is the script
you will point to when linking to MiG.  It then loads the rest of its
code from the F<mig> subdirectory.  That is done to make things cleaner
so MiG doesn't litter files all over your PHP-Nuke base directory.

4. You will need to copy the F<mig.cfg.default> sample configuration from
the F<mig> subfolder into your PHP-Nuke root directory and call it
F<mig.cfg>.  In other words:

    cd {php-nuke-root-directory}
    cp mig/mig.cfg.default ./mig.cfg
    vi mig.cfg

5. The F<mig.cfg> file should already have the two things you absolutely
need (C<$phpNukeCompatible> and C<$phpNukeRoot>).  Tune the other
parameters to whatever you see fit.

Make sure you can write to your phpNuke directory when installing.
If not, su to root, or log in as the user who owns the site prior to
running the install program.

=cut

