<!-- location -->
<center>
<strong>%%youAreHere%%</strong>
<br />
</center>

<!-- navigation -->
<center>
<small>%%backLink%%<br /></small>
<br />
</center>

<!-- folder list -->
<center>
%%folderList%%
<br />
</center>

<!-- image list -->
<center>
%%imageList%%
<br />
</center>

<!-- bulletin -->
<center>
%%description%%
</center>

<!-- navigation -->
<center>
<small>%%prevLink%% %%nextLink%% %%backLink%%<br /></small>
<br />
</center>

<!-- site info -->
<center>
<small>
<i>This page generated by <a href="%%distURL%%">Mig %%version%%</a>.</i>
</small>
</center>

