<center>
<br>
%%youAreHere%%<br>
%%backLink%%
%%folderList%%
%%imageList%%
%%description%%
<center>
%%backLink%%
<font size="-1"><i>This page generated by <a href="%%distURL%%">MiG %%version%%</a></i>.
</center>
