
<!-- location -->
<center>
 <strong>%%youAreHere%%&nbsp;&nbsp;(%%currPos%%)<br /></strong>
</center>

 <!-- navigation -->
<center>
 <small>%%prevLink%% %%nextLink%% %%backLink%%<br /></small>
 <br />
</center>

<!-- image display -->
<center>
 <img src="%%albumURLroot%%/%%newCurrDir%%/%%largeSubdir%%/%%encodedImageURL%%"
      alt="%%image%%" %%imageSize%% /><br/>
 <br />
</center>

<!-- image description -->
<center>
<table summary="Description Frame" width="60%" border="0" cellpadding="0" cellspacing="0"><tbody>
 <tr><td class="desc">
  <center>%%description%%</center>
 </td></tr>
</tbody></table>
</center>

 <!-- navigation and site info -->
<center>
 <small>%%prevLink%% %%nextLink%% %%backLink%%</small>
 <br />
</center>

<center>
 <small>
  <br />
  <i>This page generated by <a href="%%distURL%%">Mig %%version%%</a>.</i>
 </small>
</center>

