 <!-- location -->
<center>
 <strong>%%youAreHere%%&nbsp;&nbsp;(%%currPos%%)<br /></strong>
</center>

 <!-- navigation -->
<center>
 <small>%%prevLink%% %%nextLink%% %%backLink%% %%largeLink%%<br /></small>
 <br />
</center>

<!-- image display -->
<center>
%%largeHrefStart%%<img
    src="%%albumURLroot%%/%%newCurrDir%%/%%encodedImageURL%%"
    alt="%%image%%" %%imageSize%%%%largeLinkBorder%%>%%largeHrefEnd%%<br/>
 <br />
</center>

<!-- image description -->
<center>
%%description%%
</center>

 <!-- navigation and site info -->
<center>
 <small>%%prevLink%% %%nextLink%% %%backLink%% %%largeLink%%</small>
 <br />
</center>

<center>
 <small>
  <br />
  <i>This page generated by <a href="%%distURL%%">Mig %%version%%</a>.</i>
 </small>
</center>

