 <!-- location -->
<center>
 <strong>%%youAreHere%%&nbsp;&nbsp;(%%currPos%%)<br /></strong>
</center>

 <!-- navigation -->
<center>
 <small>%%prevLink%% %%nextLink%% %%backLink%%<br /></small>
 <br />
</center>

<!-- image display -->
<center>
 <img src="%%albumURLroot%%/%%newCurrDir%%/%%encodedImageURL%%"
      alt="%%image%%" %%imageSize%%><br/>
 <br />
</center>

<!-- image description -->
<center>
%%description%%
</center>

 <!-- navigation and site info -->
<center>
 <small>%%prevLink%% %%nextLink%% %%backLink%%</small>
 <br />
</center>

<center>
 <small>
  <br />
  <i>This page generated by <a href="%%distURL%%">Mig %%version%%</a>.</i>
 </small>
</center>

